resource_group_name          = "cloud-shell-storage-centralindia"
location                    = "Central India"
azurerm_public_ip          = "alb1343"
azurerm_lb                 = "azlb1343"
frontend_ip_configuration  = "fip1343"
